### ISSUE TITLE
Be able to add a comment in 'Active' state

### ISSUE THREAD

**Issue by mholloway24** [tlaukkanen/azure-devops-pr-comment-extension#1]
By default, this extension adds a comment in the `Closed` state. Being able to add a comment in `Active` would make more sense but allowing users to specify the created state would provide the most flexibility

**Comment by tlaukkanen** [comment]
@mholloway24 clever idea. That would allow for example to raise issues related to builds like security stuff or whatever. Should be there now:
![image](https://github.com/tlaukkanen/azure-devops-pr-comment-extension/assets/65841/c646befa-b0d8-49e0-9108-a75bc92163bb)

**Comment by tlaukkanen** [comment]
Just a note that default value will still remain `false` so this doesn't break any pipelines 😃
