### ISSUE TITLE
Warning about Node version 

### ISSUE THREAD

**Issue by klamfeldt** [tlaukkanen/azure-devops-pr-comment-extension#6]
Hi

I had a different extension but switched to yours since it's maintained but unfortunately I get the same warning in the pipeline for this extension. 
Is this something that you would like to look into?

##[warning]Task 'Pull Request Comment' version 1 (PullRequestComment@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

Best Regards
Pontus

**Comment by tlaukkanen** [comment]
Well spotted. I'll increase the Node version in next release later this week.

**Comment by tlaukkanen** [comment]
@klamfeldt new version 1.3.0 of the task released with Node.js 16 & 20 support.
