### ISSUE TITLE
Comments for every build

### ISSUE THREAD

**Issue by klamfeldt** [tlaukkanen/azure-devops-pr-comment-extension#8]
Hi

We have replaced our extension for PR comments from another extension to your extension but one difference is that this extension add a comment for each time the PR is build, not just the first time which we think is enough.

 
![Skärmbild 2024-11-05 094045](https://github.com/user-attachments/assets/3e7da36e-784f-4cd4-9b6a-722ff6668854)

**Comment by tlaukkanen** [comment]
Good idea, so the feature could be adding a new parameter like `addCommentOnlyOnce: true` so that it wouldn't add a new one if previous exists or `replacePreviousComment: true` that could update the comment text in the original comment. Maybe both could have some different use-cases.

I'll check on implementing these later this week 🙂

**Comment by tlaukkanen** [comment]
...and just as additional comment - I've worked with many teams that utilize Pull Request Templates for that kind of "checks":
https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops#default-pull-request-templates

**Comment by klamfeldt** [comment]
Yes we used pull requests templates as well before but the team like comments better then in the description.
Our team would preferer `addCommentOnlyOnce: true` since they normally close the comment if they did all the reminders and don't want a new one if they had to change something small in the PR like smelling mistake etc. So only add the comments once.

Best regards 
Pontus

**Comment by tlaukkanen** [comment]
@klamfeldt ok, should be now working. You can try with either `addCommentOnlyOnce: false` or `updatePreviousComment: true`

**Comment by klamfeldt** [comment]
Thanks it works!
